torizoncore-builder: Log output of failing commands
During build, commands like tar are ran. When they would fail,
a CalledProcessError would raise to the top and be printed, but this
includes a backtrace but not the command output. In case of for example
tar failures, this would provide no hint what was wrong.

This commit catches such exceptions and prints them with the command
output. A backtrace is only printed in debug log level.

For example, when unpacking a non-existent tarball, you get:

    $ torizoncore-builder images unpack nonexistent-Tezi_6.2.0+build.2.tar
    Storage not empty. Delete current image before continuing? [y/N] y
    Unpacking Toradex Easy Installer image.
    Command 'cat /workdir/nonexistent-Tezi_6.2.0+build.2.tar | cat | tar -xf - -C /storage/tezi.tmp' returned non-zero exit status 2.
    Output:
      cat: /workdir/nonexistent-Tezi_6.2.0+build.2.tar: No such file or directory
      tar: This does not look like a tar archive
      tar: Exiting with failure status due to previous errors

Instead of (backtrace ommitted for brevity):

    $ torizoncore-builder images unpack nonexistent-Tezi_6.2.0+build.2.tar
    Storage not empty. Delete current image before continuing? [y/N] y
    Unpacking Toradex Easy Installer image.
    An unexpected Exception occurred. Please provide the following stack trace to
    the Toradex TorizonCore support team:

    Traceback (most recent call last):
	[ SNIP BACKTRACE ]
    subprocess.CalledProcessError: Command 'cat /workdir/nonexistent-Tezi_6.2.0+build.2.tar | cat | tar -xf - -C /storage/tezi.tmp' returned non-zero exit status 2.

This fixes #10.

Signed-off-by: Matthijs Kooijman <matthijs@stdin.nl>