torizoncore-builder: Fix exception field access
Check the "output" field of an exception object before accessing its
contents. In some cases, an exception may be thrown with that field not
set which would cause a traceback to be dumped besides the actual error
message. This was detected when testing "filesystem" changes with the
.tcattr file having files not actually present in the changes directory.

Here's a stretch of the build command output showing that situation:

  =>> Handling output section
  setfacl: shadow: No such file or directory
  setfacl: mtab: No such file or directory
  setfacl: locale.conf: No such file or directory
  setfacl: vconsole.conf: No such file or directory
  Command '['setfacl', ...]' returned non-zero exit status 1.

  Traceback (most recent call last):
    File "/builder/torizoncore-builder", line 232, in <module>
      mainargs.func(mainargs)
  ...
  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/builder/torizoncore-builder", line 243, in <module>
      if b"\n" in ex.output:
  TypeError: argument of type 'NoneType' is not iterable

Signed-off-by: Rogerio Guerra Borin <rogerio.borin@toradex.com>